### ISSUE TITLE
Board selection for Platform.IO?

### ISSUE THREAD

**Issue by rkeniger** [luminationlabs/Sonatino-Examples#2]
I'm trying to use the Sonatino with platform.io but there is no custom board definition that I can see. 

My current platformio.ini file is as follows:

```
[env:sonatino]
platform = espressif32
board = esp32s3box
framework = arduino
lib_deps = 
    pschatzmann/audio-tools@^0.9.8
    git@github.com:pschatzmann/arduino-libhelix.git@^0.8.5
build_flags = 
  -DCORE_DEBUG_LEVEL=1
  -DARDUINO_USB_CDC_ON_BOOT=1 
```

The `esp32s3box` was the closest board I could find to the Sonatino's ESP32 specs.

Do you have a custom board definition we can use with platformIO? Or is there a better choice from the built-in ones?

**Comment by lumination-labs** [comment]
There is not currently a custom board definition for PlatformIO. [One of the examples](https://github.com/luminationlabs/Sonatino-Examples/blob/main/streaming/platformio.ini) uses `esp32-s3-devkitc-1`, but it looks like `esp32s3box` might actually be closer since it's already configured for 16MB flash and PSRAM.

I'm not super familiar with PlatformIO board definitions, so if you have any suggestions or pull requests, I'm happy to consider merging them or making necessary changes.

**Comment by rkeniger** [comment]
Yeah, it does seem to be working thus far and I've confirmed that I can make use of the additional RAM etc by choosing partitioning schemes with large app sections. If you think it's OK to continue with `esp32s3box` then I'll do that.

Thanks for your prompt response.
